In [13]:
import numpy as np
array_list = [[100, 65, 160],
[150, 82, 200],
[90, 55, 80],
[130, 73, 220],
[190, 80, 150]]

array_list[1][2]

array_list[3][0]

import array as arr
arr_x = arr.array("d", [98.6, 22.35, 72.1])


In [15]:
array1d = np.array([1, 2, 3, 4])
array2d = np.array([[0, 1, 2],[2, 3, 4]])

In [17]:
np.ones((2, 3, 4))
np.zeros((2, 1, 3))
np.identity(3)
np.eye(N = 3)
np.eye(N = 2, M = 3)
np.eye(N = 4, M = 3, k = 1)
np.eye(N = 4, M = 3, k = -2)

np.arange(6)
np.arange(2, 13, 3)
np.linspace(start = 5, stop = 10, num = 20)


array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [19]:
np.random.rand(2, 4)
np.random.randn(2, 4)
5 * np.random.randn(2, 4) + 10
np.random.randint(2, 5, (2, 3))
np.empty([4,3])
arr_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.diag(arr_a)
np.diag(np.diag(arr_a))
np.diag(np.diag(arr_a, k = 1))

np.tile(np.array([1, 2, 3]), 2)
np.tile(np.array([[1, 2, 3], [4, 5, 6]]), 4)
np.tile(np.array([[1, 2, 3], [4, 5, 6]]), (4,1))
np.array([-2, -1, 0, 1, 2]).dtype
np.array([-2, -1, 0, 1, 2], dtype = "float")
np.array([-2, -1, 0, 1, 2], dtype = "str")
np.array(["a", "bb", "ccc", "dddd", "eeeee"])
np.array([True, False, True, True]).dtype
np.array([0, 1, 1, 0, 0], dtype = "bool")
np.array([0, 1, 2, 3, -4], dtype = "bool")
np.array([[1 + 1j, 2 + 2j], [3 + 3j, 4 + 4j]])
np.array([[1 + 1j, 2 + 2j], [3 + 3j, 4 + 4j]]).dtype

int_array = np.array([0, 1, 2, 3])
int_array.astype("float")
float_array = np.array([1.56, 2.95, 3.12, 4.65])
float_array.astype("int")

array([1, 2, 3, 4])

In [23]:
ar = np.arange(5); print (ar); ar[0], ar[1], ar[-1]
ar=np.arange(5); ar[1], ar[-1], ar[0]
ar=np.arange(5); ar[::-1]
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])
ar[1,1]
ar[1,1]=5
ar[2]
ar[:,1]
ar = np.array([0,1,2])
ar=2*np.arange(6)
ar[1:6:2]
ar[:4]
ar[4:]
ar[::3]
ar
ar[:3]=1; ar
ar[2:]=np.ones(4)

[0 1 2 3 4]


In [27]:
np.random.seed(10)
ar=np.random.random_integers(0,25,10)
evenMask=(ar % 2==0); evenMask
evenNums=ar[evenMask]; evenNums
ar=np.array(['Hungary','Nigeria', 'Guatemala','','Poland','','Japan']); ar
ar[ar=='']='USA'; ar
ar=11*np.arange(0,10); ar
ar[[1,3,4,2,7]]
ar[[1,3]]=50; ar
ar=np.arange(15); ar
ar2=np.arange(0,-10,-1)[::-1]; ar2
ar[:10]=ar2; ar

/var/folders/dv/3stz4zmn5jn1dhpcpw10k25h0000gp/T/ipykernel_51298/898764788.py:2: DeprecationWarning: This function is deprecated. Please call randint(0, 25 + 1) instead
  ar=np.random.random_integers(0,25,10)


array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0, 10, 11, 12, 13, 14])

In [29]:
ar1=np.arange(12); ar1
ar2=ar1[::2]; ar2
ar2[1]=-1; ar1
ar=np.arange(8);ar
arc=ar[:3].copy(); arc
arc[0]=-1; arc
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_1 + 5
array_1 * 5
array_1 ** 2

array_1 + array_1
array_1 * array_1
array_1 @ array_1.T

array([[14, 32],
       [32, 77]])

In [31]:
%timeit np.arange(1000) ** 3
array_list = range(1000)
%timeit [array_list[i]**3 for i in array_list]

np.array([[1, 2, 3], [4, 5, 6]]).sum()
np.array([[1, 2, 3], [4, 5, 6]]).sum(axis = 0)
np.array([[1, 2, 3], [4, 5, 6]]).cumsum(axis = 0)
np.array([[1, 2, 3], [4, 5, 6]]).cumsum()
array_x = np.array([[0, 1, 2], [3, 4, 5]])
np.mean(array_x)
np.median(array_x)
np.var(array_x)
np.std(array_x)
np.mean(array_x, axis = 0)
np.mean(array_x, axis = 1)


1.72 µs ± 12.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
46.3 µs ± 380 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


array([1., 4.])

In [33]:
nan_array = np.array([[5, 6, np.nan], [19, 3, 2]])
np.median(nan_array)
np.nanmedian(nan_array)


5.0

In [35]:
array_corr = np.random.randn(3,4)
array_corr
np.corrcoef(array_corr)
np.cov(array_corr)
array_logical = np.random.randn(3, 4)
np.any(array_logical < 0, axis = 0)
np.all(array_logical < 0)
np.isfinite(np.array([12, np.inf, 3, np.nan]))
np.isnan((np.array([12, np.inf, 3, np.nan])))
np.isinf((np.array([12, np.inf, 3, np.nan])))

array([False,  True, False, False])

In [37]:
array1 = np.random.randn(3,4)
array2 = np.random.randn(3, 4)
np.greater(array1, array2)
np.less(array1, array2)

array([[False,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True, False,  True]])

In [39]:
ar=np.ones([3,2]); ar
ar2=np.array([2,3]); ar2
ar+ar2
ar=np.array([[23,24,25]]); ar
ar.T
ar.T+ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])

In [41]:
reshape_array = np.arange(0,15)
np.reshape(reshape_array, (5, 3))
trans_array = np.arange(0,24).reshape(4, 6)
trans_array.T
trans_array = np.arange(0,24).reshape(2, 3, 4)
trans_array.T.shape


(4, 3, 2)

In [43]:
ravel_array = np.arange(0,12).reshape(4, 3)
ravel_array.ravel()
ravel_array.ravel(order = "F")

array([ 0,  3,  6,  9,  1,  4,  7, 10,  2,  5,  8, 11])

In [45]:
array_x = np.array([0, 1, 2, 3, 4, 5, 6])
array_x[:, np.newaxis]
array_x[:, np.newaxis].shape
array_x[:, np.newaxis, np.newaxis]
array_x[:, np.newaxis, np.newaxis].shape


(7, 1, 1)

In [47]:
array_1 = np.random.randn(2, 4)
array_2 = np.random.randn(4, 2)
np.dot(array_1, array_2)

array([[ 3.10689567, -4.20433218],
       [-0.15837941,  0.6605727 ]])

In [49]:
array_1 = np.random.randn(2, 4, 2)
array_2 = np.random.randn(1, 1, 2, 1)
np.dot(array_1, array_2).shape


(2, 4, 1, 1, 1)

In [51]:
array_svd = np.random.randn(4, 3)
np.linalg.svd(array_svd)
np.linalg.eig(np.random.randn(5, 5))

EigResult(eigenvalues=array([2.20560487+0.j        , 0.5947018 +1.63409537j,
       0.5947018 -1.63409537j, 0.10123614+0.j        ,
       0.38585436+0.j        ]), eigenvectors=array([[ 4.87683648e-01+0.j        ,  4.22408431e-01-0.07052932j,
         4.22408431e-01+0.07052932j, -9.04462019e-01+0.j        ,
         9.17796064e-01+0.j        ],
       [-9.94847786e-02+0.j        , -1.10642428e-01-0.36051319j,
        -1.10642428e-01+0.36051319j, -1.12010026e-01+0.j        ,
        -7.82501618e-03+0.j        ],
       [-6.95653774e-01+0.j        ,  7.39343851e-02-0.21609392j,
         7.39343851e-02+0.21609392j, -3.53889940e-04+0.j        ,
        -5.06226269e-02+0.j        ],
       [ 2.59331373e-01+0.j        ,  1.89842224e-01-0.49068765j,
         1.89842224e-01+0.49068765j, -3.66981019e-01+0.j        ,
         3.24668397e-01+0.j        ],
       [-4.48420009e-01+0.j        , -5.87714142e-01+0.j        ,
        -5.87714142e-01-0.j        ,  1.86351863e-01+0.j        ,
        -2

In [53]:
a = np.array([[1, 2, 3], [5, 4, 2], [8, 9, 7]])
b = np.array([6, 19, 47])
np.linalg.solve(a, b)

array([-6.27272727, 15.81818182, -6.45454545])

In [55]:
np.linalg.det(np.random.randn(3,3))
np.linalg.det(np.random.randn(2,3,3))


array([-1.49068268,  0.26356622])

In [57]:
ar=np.array([[3,2],[10,-1]])
ar.sort(axis=1)
ar=np.array([[3,2],[10,-1]])
ar.sort(axis=0)


In [71]:
N = 1000
X1 = np.random.randn(N, 2) + np.array([0.9, 0.9])
X2 = np.random.randn(N, 2) + np.array([-0.9, -0.9])
Y1 = np.zeros((N, 1))
Y2 = np.ones((N, 1))
X = np.vstack((X1, X2))
Y = np.vstack((Y1, Y2))
train = np.hstack((X, Y))
x = train[:, 0:2]
t = train[:, 2].reshape(2000, 1)
def sigmoid(x, derive = False):
    if (derive == True):
        return x * (1 - x)
    else:
        return 1 / (1 + np.exp(-x))	
x_in = np.concatenate([x, np.repeat([[1]], 2000, axis = 0)], axis = 1)
w_ih = np.random.normal(size = (3, 3))
y_h = np.dot(x_in, w_ih)
a_h = sigmoid(y_h)
a_hin = np.concatenate([a_h, np.repeat([[1]], 2000, axis = 0)], axis = 1)
w_ho = np.random.normal(size = (4, 1))
y_o = np.dot(a_hin, w_ho)
a_o = sigmoid(y_o)
delta_a_o_error = a_o - t
delta_y_o = sigmoid(a_o, derive=True)
delta_w_ho = a_hin
delta_output_layer = np.dot(delta_w_ho.T,(delta_a_o_error * delta_y_o))

In [82]:
delta_a_h = np.dot(delta_a_o_error * delta_y_o, w_ho[0:3,:].T)
delta_y_h = sigmoid(a_h, derive=True)
delta_w_ih = x_in
delta_hidden_layer = np.dot(delta_w_ih.T, delta_a_h * delta_y_h)
eta = 0.1
w_ih = w_ih - eta * delta_hidden_layer
w_ho = w_ho - eta * delta_output_layer
x = train[:,0:2]
t = train[:,2].reshape(2000,1)
x_in = np.concatenate([x, np.repeat([[1]], 2000, axis = 0)], axis = 1)
w_ih = np.random.normal(size = (3, 3))
w_ho = np.random.normal(size = (4, 1))
def sigmoid(x, derive = False):
    if (derive == True):
        return x * (1 - x)
    else:
        return 1 / (1 + np.exp(-x))
epochs = 5000
eta = 0.1
for epoch in range(epochs):
# Feed forward
    y_h = np.dot(x_in, w_ih)
    a_h = sigmoid(y_h)
    a_hin = np.concatenate([a_h, np.repeat([[1]], 2000, axis = 0)],     axis = 1)
    y_o = np.dot(a_hin, w_ho)
    a_o = sigmoid(y_o)

    # Calculate the error
    a_o_error = ((1 / 2) * (np.power((a_o - t), 2)))

    # Backpropagation
    ## Output layer
    delta_a_o_error = a_o - t
    delta_y_o = sigmoid(a_o, derive=True)
    delta_w_ho = a_hin
    delta_output_layer = np.dot(delta_w_ho.T,(delta_a_o_error * delta_y_o))

    ## Hidden layer
    delta_a_h = np.dot(delta_a_o_error * delta_y_o, w_ho[0:3,:].T)
    delta_y_h = sigmoid(a_h, derive=True)
    delta_w_ih = x_in
    delta_hidden_layer = np.dot(delta_w_ih.T, delta_a_h * delta_y_h)
    w_ih = w_ih - eta * delta_hidden_layer
    w_ho = w_ho - eta * delta_output_layer
    print(a_o_error.mean())

TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

In [84]:
import cv2
import matplotlib.pyplot as plt
import os
os.chdir('')
img=cv2.imread('view.jpg')
img2=cv2.imread('rose.jpg')

print(type(img))
img.shape
plt.imshow(img)
img_r=img[:,:,0]
plt.imshow(img_r) 
img_g=img[:,:,1]
plt.imshow(img_g)
img_b=img[:,:,2]
plt.imshow(img_b)
img_tree=img[50:155,95:190,:]
plt.imshow(img_tree)
img3=img
img3[50:155,1:96,:]=img_tree
plt.imshow(img3) 
fig, axes = plt.subplots(1, 3)

ModuleNotFoundError: No module named 'cv2'

In [96]:
import numpy as np
import pandas as pd
import calendar as cal

#ser = pd.Series(data, index=idx)  # This requires 'data' and 'idx' to be defined
ser = pd.Series(np.random.randn(7))  # Series with random values

monthNames = [cal.month_name[i] for i in np.arange(1, 6)]
months = pd.Series(np.arange(1, 6), index=monthNames)
months.index

monthNames = [cal.month_name[i] for i in np.arange(1, 6)]
months = pd.Series(np.arange(1, 6), index=monthNames)
months.index

currDict = {'US': 'dollar', 'UK': 'pound', 'Germany': 'euro', 'Mexico': 'peso', 'Nigeria': 'naira', 'China': 'yuan', 'Japan': 'yen'}
currSeries = pd.Series(currDict)

stockPrices = {'GOOG': 1180.97, 'FB': 62.57, 'TWTR': 64.50, 'AMZN': 358.69, 'AAPL': 500.6}
stockPriceSeries = pd.Series(stockPrices, index=['GOOG', 'FB', 'YHOO', 'TWTR', 'AMZN', 'AAPL'], name='stockPrices')

dogSeries = pd.Series('chihuahua', index=['breed', 'countryOfOrigin', 'name', 'gender'])

currDict['China']
stockPriceSeries['GOOG'] = 1200.0
stockPriceSeries.get('MSFT', np.NaN)  # Corrected method
stockPriceSeries[:4]
stockPriceSeries[stockPriceSeries > 100]
np.mean(stockPriceSeries)
np.std(stockPriceSeries)
ser
ser * ser
ser[1:]
ser[1:] + ser[:-2]

stockSummaries = {
    'AMZN': pd.Series([346.15, 0.59, 459, 0.52, 589.8, 158.88],
                      index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'Beta', 'P/E', 'Market Cap(B)']),
    'GOOG': pd.Series([1133.43, 36.05, 335.83, 0.87, 31.44, 380.64],
                      index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'Beta', 'P/E', 'Market Cap(B)']),
    'FB': pd.Series([61.48, 0.59, 2450, 104.93, 150.92],
                    index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Market Cap(B)']),
    'YHOO': pd.Series([34.90, 1.27, 1010, 27.48, 0.66, 35.36],
                      index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Beta', 'Market Cap(B)']),
    'TWTR': pd.Series([65.25, -0.3, 555.2, 36.23],
                      index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'Market Cap(B)']),
    'AAPL': pd.Series([501.53, 40.32, 892.45, 12.44, 447.59, 0.84],
                      index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Market Cap(B)', 'Beta'])
}

stockDF = pd.DataFrame(stockSummaries)

stockDF = pd.DataFrame(stockSummaries,
                       index=['Closing price', 'EPS', 'Shares Outstanding(M)', 'P/E', 'Market Cap(B)', 'Beta'],
                       columns=['FB', 'TWTR', 'GOOG'])

stockDF.index
stockDF.columns

algos = {'search': ['DFS', 'BFS', 'Binary Search', 'Linear', 'ShortestPath (Dijkstra)'],
         'sorting': ['Quicksort', 'Mergesort', 'Heapsort', 'Bubble Sort', 'Insertion Sort'],
         'machine learning': ['RandomForest', 'K Nearest Neighbor', 'Logistic Regression', 'K-Means Clustering', 'Linear Regression']}

algoDF = pd.DataFrame(algos)
algoDF
pd.DataFrame(algos, index=['algo_1', 'algo_2', 'algo_3', 'algo_4', 'algo_5'])






search         sorting     machine learning
algo_1                      DFS       Quicksort         RandomForest
algo_2                      BFS       Mergesort   K Nearest Neighbor
algo_3            Binary Search        Heapsort  Logistic Regression
algo_4                   Linear     Bubble Sort   K-Means Clustering
algo_5  ShortestPath (Dijkstra)  Insertion Sort    Linear Regression

In [102]:
import numpy as np
import pandas as pd

memberData = np.array([('Sanjeev', 37, 162.4),
                       ('Yingluck', 45, 137.8),
                       ('Emeka', 28, 153.2),
                       ('Amy', 67, 101.3)],
                      dtype=[('Name', 'U15'), ('Age', 'i4'), ('Weight', 'f4')])

memberDF = pd.DataFrame(memberData)

pd.DataFrame(memberData, index=['a', 'b', 'c', 'd'])  # Indexed DataFrame
pd.DataFrame(memberData, columns=["Weight", "Name", "Age"])  # Rearranged columns

demographicData = [{"Age": 32, "Gender": "Male"}, {"Race": "Hispanic", "Gender": "Female", "Age": 26}]
demographicDF = pd.DataFrame(demographicData)

salesData = {("2012", "Q1"): {("North", "Brand A"): 100, ("North", "Brand B"): 80, ("South", "Brand A"): 25, ("South", "Brand B"): 40},
             ("2012", "Q2"): {("North", "Brand A"): 30, ("South", "Brand B"): 50},
             ("2013", "Q1"): {("North", "Brand A"): 80, ("North", "Brand B"): 10, ("South", "Brand B"): 25},
             ("2013", "Q2"): {("North", "Brand A"): 70, ("North", "Brand B"): 50, ("South", "Brand A"): 35, ("South", "Brand B"): 40}}

salesDF = pd.DataFrame(salesData)

currDict = {'US': 'dollar', 'UK': 'pound', 'Germany': 'euro', 'Mexico': 'peso', 'Nigeria': 'naira', 'China': 'yuan', 'Japan': 'yen'}
currSeries = pd.Series(currDict)
currDF = pd.DataFrame(currSeries, columns=["Currency"])

# Assuming 'algos' is a predefined dictionary
algos = {
    'search': ['DFS', 'BFS', 'Binary Search', 'Linear', 'ShortestPath (Dijkstra)'],
    'sorting': ['Quicksort', 'Mergesort', 'Heapsort', 'Bubble Sort', 'Insertion Sort'],
    'machine learning': ['RandomForest', 'K Nearest Neighbor', 'Logistic Regression', 'K-Means Clustering', 'Linear Regression']
}

pd.DataFrame.from_dict(algos, orient="columns")
pd.DataFrame.from_dict(algos, orient="index", columns=["A", "B", "C", "D", "E"])
pd.DataFrame.from_records(memberData, index="Name")

memberDF["Name"]
memberDF['Height'] = 60
memberDF['Height2'] = [57, 62, 65, 59]
memberDF.insert(1, "ID", ["S01", "S02", "S03", "S04"])
del memberDF["Height"]
height2 = memberDF.pop("Height2")

ore1DF = pd.DataFrame(np.array([[20, 35, 25, 20],
                                [11, 28, 32, 29]]),
                     columns=['iron', 'magnesium', 'copper', 'silver'])

ore2DF = pd.DataFrame(np.array([[14, 34, 26, 26],
                                [33, 19, 25, 23]]),
                     columns=['iron', 'magnesium', 'gold', 'silver'])

ore1DF + ore2DF
ore1DF + pd.Series([25, 25, 25, 25], index=['iron', 'magnesium', 'copper', 'silver'])
ore1DF["add_iron_copper"] = ore1DF["iron"] + ore1DF["copper"]

logical_df1 = pd.DataFrame({'Col1': [1, 0, 1], 'Col2': [0, 1, 1]}, dtype=bool)
logical_df2 = pd.DataFrame({'Col1': [1, 0, 0], 'Col2': [0, 0, 1]}, dtype=bool)
logical_df1 | logical_df2
np.sqrt(ore1DF)

stockData = np.array([[[63.03, 61.48, 75],
                       [62.05, 62.75, 46],
                       [62.74, 62.19, 53]],
                      [[411.90, 404.38, 2.9],
                       [405.45, 405.91, 2.6],
                       [403.15, 404.42, 2.4]]])

# Note: pd.Panel is deprecated, consider using xarray or multi-index DataFrames

USData = pd.DataFrame(np.array([[249.62, 8900],
                                [282.16, 12680],
                                [309.35, 14940]]),
                      columns=['Population(M)', 'GDP($B)'],
                      index=[1990, 2000, 2010])

ChinaData = pd.DataFrame(np.array([[1133.68, 390.28],
                                   [1266.83, 1198.48],
                                   [1339.72, 6988.47]]),
                         columns=['Population(M)', 'GDP($B)'],
                         index=[1990, 2000, 2010])

US_ChinaData = pd.concat({'US': USData, 'China': ChinaData}, axis=1)

mIdx = pd.MultiIndex.from_product([['US', 'China'], [1990, 2000, 2010]], names=['Country', 'Year'])

ChinaUSDF = pd.DataFrame({'Population(M)': [249.62, 282.16, 309.35, 1133.68, 1266.83, 1339.72],
                          'GDP($B)': [8900, 12680, 14940, 390.28, 1198.48, 6988.47]}, 
                         index=mIdx)
ChinaUSDF

Population(M)   GDP($B)
Country Year                         
US      1990         249.62   8900.00
        2000         282.16  12680.00
        2010         309.35  14940.00
China   1990        1133.68    390.28
        2000        1266.83   1198.48
        2010        1339.72   6988.47